// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDlVcKDVq9M5wCGFj-F0wz2OMjAWRypxI',
    appId: '1:423808135611:web:413365060c3a32303bd49e',
    messagingSenderId: '423808135611',
    projectId: 'e-commerce-98eed',
    authDomain: 'e-commerce-98eed.firebaseapp.com',
    storageBucket: 'e-commerce-98eed.firebasestorage.app',
    measurementId: 'G-GZXD7VBPZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4GWssK6jLRn3KGRq2MhqVQIbwRscJNOI',
    appId: '1:423808135611:android:0b7a7128cb294b883bd49e',
    messagingSenderId: '423808135611',
    projectId: 'e-commerce-98eed',
    storageBucket: 'e-commerce-98eed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUtBUWi5XW-L3mtlmfqxx488w9jtQG5_w',
    appId: '1:423808135611:ios:e81d5e41fbca26133bd49e',
    messagingSenderId: '423808135611',
    projectId: 'e-commerce-98eed',
    storageBucket: 'e-commerce-98eed.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUtBUWi5XW-L3mtlmfqxx488w9jtQG5_w',
    appId: '1:423808135611:ios:e81d5e41fbca26133bd49e',
    messagingSenderId: '423808135611',
    projectId: 'e-commerce-98eed',
    storageBucket: 'e-commerce-98eed.firebasestorage.app',
    iosBundleId: 'com.example.eCommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDlVcKDVq9M5wCGFj-F0wz2OMjAWRypxI',
    appId: '1:423808135611:web:ae1ce751422ea5fc3bd49e',
    messagingSenderId: '423808135611',
    projectId: 'e-commerce-98eed',
    authDomain: 'e-commerce-98eed.firebaseapp.com',
    storageBucket: 'e-commerce-98eed.firebasestorage.app',
    measurementId: 'G-2XT5XT4HKK',
  );
}
